
let optionsSwagger = {
    swaggerDefinition: {
        // Like the one described here: https://swagger.io/specification/#infoObject
        info: {
          title: 'Mantina API',
          version: '1.0.0',
          description: 'Test Express API with autogenerated swagger doc',
        },
        host: 'localhost:8080',
        basePath: '',
        produces: [
            "application/json",
            "application/xml"
        ],
      },
      // List of files to be processes. You can also set globs './routes/*.js'
      apis: ['./routes/*.js'],
    };

module.exports = optionsSwagger;